version: "3.7"

#Laravel
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www:rw
    container_name: backend
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    container_name: nginx
    networks:
      - laravel

  # db mysql
  db:
    image: mysql:5.7.22
    restart: always  
    environment:  
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: user_teste
    volumes:  
      - /data/:/var/lib/mysql
    container_name: db
    ports:
      - "3306:3306"
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025 
    container_name: mailhog
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
