#Laravel
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www:rw
    container_name: backend
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    container_name: nginx
    networks:
      - laravel

  # db mysql
  db:
    image: postgres
    restart: always  
    environment:  
      POSTGRES_DB: laravel
      POSTGRES_USER: user_teste
      POSTGRES_PASSWORD: root
    volumes:  
      - /data/:/var/lib/postgresql/data
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
